"""Criar Tabela Bancos

Revision ID: 5856670dcd4b
Revises: e61bcc4cc777
Create Date: 2026-07-22 23:37:04.432651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5856670dcd4b'
down_revision = 'e61bcc4cc777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bancos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bancos')
    # ### end Alembic commands ###
