"""Criar a tabela Saldos

Revision ID: d94e8018592b
Revises: 8289c409989a
Create Date: 2026-07-23 04:00:05.329739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94e8018592b'
down_revision = '8289c409989a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saldos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('banco_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('ano >= 2026', name='check_ano_valido'),
    sa.CheckConstraint('mes >= 1 AND mes <= 12', name='check_mes_valido'),
    sa.ForeignKeyConstraint(['banco_id'], ['bancos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano', 'mes', 'banco_id', 'user_id', name='unique_ano_mes_banco_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saldos')
    # ### end Alembic commands ###
